app:
  name: 'lemon_be'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'lemon_be'

firestore:
  projectId: "491496864435"
  service_acc_key: "/Users/lintangbirdasaputra/Documents/sekolah/gdsc/GSC_Lemon/lemon_app_baru/lemon_be/lemon-df113-firebase-adminsdk-d0bb7-c8586e988d.json"



